# Generated by Django 3.1.7 on 2021-07-01 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_reservationroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 21, 51, 4, 420219, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 21, 51, 9, 982991, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='person',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='checkin',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 1, 21, 51, 27, 82334, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='checkout',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 1, 21, 51, 30, 566881, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='person',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
