# Generated by Django 3.1.7 on 2021-07-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20210702_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='person',
            new_name='adults',
        ),
        migrations.RenameField(
            model_name='reservationroom',
            old_name='person',
            new_name='adults',
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='children',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
