# Generated by Django 3.1.7 on 2021-07-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20210702_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='quantity',
            new_name='days',
        ),
    ]
