# Generated by Django 3.1.7 on 2021-07-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20210702_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='days',
            field=models.IntegerField(blank=True),
        ),
    ]
