# Generated by Django 3.1.7 on 2021-07-02 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20210702_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationroom',
            old_name='quantity',
            new_name='days',
        ),
    ]
